### ISSUE TITLE
DSDT 你是怎么制作的？

### ISSUE THREAD

**Issue by DearTanker** [liaobinbin/hackintosh#2]
好奇你的U是怎么做到可以识别为至强的，我现在是E3-1231v 3、主板是技嘉凤凰B85 ITX。感觉我们的配置挺接近的。

**Comment by liaobinbin** [comment]
这个应该不是他识别的，是在配置文件里面手动写的类型，然后配上ssdt这些，很久没弄了，具体我也请不清楚是哪个文件了

**Comment by liaobinbin** [comment]
我看了一下你的标题，你在问DSDT是怎么制作的，其实我DSDT是拷贝被人同主板的，自己没做什么修改。 没多大的必要，修改那个比较花费时间。

**Comment by DearTanker** [comment]
DSDT只跟主板有关吗？这个DSDT用上去会有啥好处。

**Comment by liaobinbin** [comment]
@DearTanker dsdt不只是主板吧，也可以说是主板，好像是系统会通过dsdt识别硬件，在dsdt里面就可以实现各种仿冒硬件，前提你会的话，所以不断优化dsdt，理论上可以非常接近白果。
